commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - moneylogger-k8s/moneylogger-deployment.yml
  - moneylogger-k8s/moneylogger-service.yml
  - moneylogger-k8s/moneylogger-postgresql.yml
  - moneyloggergw-k8s/moneyloggergw-deployment.yml
  - moneyloggergw-k8s/moneyloggergw-service.yml
  - moneyloggergw-k8s/moneyloggergw-postgresql.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
