apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: tphucnha/moneylogger
      context: ../moneylogger
      jib: {}
    - image: tphucnha/moneyloggergw
      context: ../moneyloggergw
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
