apiVersion: v1
kind: Service
metadata:
  name: moneyloggergw
  namespace: default
  labels:
    app: moneyloggergw
spec:
  selector:
    app: moneyloggergw
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
